# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
window:
  opacity: 0.9
  decorations: none
  startup_mode: Maximized

scrolling:
  history: 0
  multiplier: 3

font:
  size: 18
  offset:
    x: 0
    y: 1
  normal:
    family: Menlo
    # style: Light

bell:
  animation: EaseOutCubic
  duration: 0
  color: '#444444'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

shell:
  program: /opt/homebrew/bin/tmux
  args:
    - new-session
    - -A
    - -s
    - base
    - -c
    - /Users/qiqi/Downloads

colors:
  primary:
    background: '#1e1e1e'
    foreground: '#d4d4d4'
  cursor:
    text: CellBackground
    cursor: CellForeground
  normal:
    black:   '#1e1e1e'
    red:     '#f44747'
    green:   '#608b4e'
    yellow:  '#dcdcaa'
    blue:    '#569cd6'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#d4d4d4'
  bright:
    black:   '#545454'
    red:     '#f44747'
    green:   '#608b4e'
    yellow:  '#dcdcaa'
    blue:    '#569cd6'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#d4d4d4'


# https://www.eso.org/~ndelmott/ascii.html
# <C-L> \x0c; <C-X> \x18; <C-S> \x13
key_bindings:
  # for tmux
  - { key: T, mods: Command, chars: "\x13\x63" } # create new window
  - { key: Comma, mods: Command, chars: "\x13\x2c" } # rename window
  - { key: K, mods: Command, chars: "\x13\x73" } # select sessions
  - { key: Y, mods: Command|Shift, chars: "\x13\x79" } # open popup "<prefix> y"
  - { key: LBracket, mods: Command|Shift, chars: "\x13\x70" } # previous window
  - { key: RBracket, mods: Command|Shift, chars: "\x13\x6e" } # next window
  - { key: N, mods: Command, chars: "\x13\x25" } # split, left&right
  - { key: N, mods: Command|Shift, chars: "\x13\x22" } # split, top&bottom
  - { key: W, mods: Command, chars: "\x13\x26" } # kill window
  - { key: Key0, mods: Command, chars: "\x13\x30" } # select window 0
  - { key: Key1, mods: Command, chars: "\x13\x31" } # select window 1
  - { key: Key2, mods: Command, chars: "\x13\x32" } # select window 2
  - { key: Key3, mods: Command, chars: "\x13\x33" } # select window 3
  - { key: Key4, mods: Command, chars: "\x13\x34" } # select window 4
  - { key: Key5, mods: Command, chars: "\x13\x35" } # select window 5
