#!/bin/sh
[ -z "$PS1" ] && return

# basic config
local_dir="$HOME/.local"

# Homebrew
brew_path="/opt/homebrew/bin/brew"
[ -f $brew_path ] && [ -z $HOMEBREW_PREFIX ] &&\
    eval "$($brew_path shellenv | grep -v 'export PATH')"

# Handle PATH
[ -d "$HOME/nq/bin" ] &&\
    nqitembin="$HOME/nq/bin" nqbin="$HOME/nq/bin" ||\
    nqitembin="$local_dir/bin" nqbin="$HOME/.config/nq/bin"

subpath="$HOME/go/bin:$nqitembin:$nqitembin/node:$nqbin"
subpath="$subpath:$local_dir/conda/bin:$HOME/.cargo/bin"
[ -f $brew_path ] &&\
    subpath="$subpath:/opt/homebrew/bin:/opt/homebrew/sbin"

case $PATH in 
    *conda*) export PATH="$subpath:${PATH/$subpath}";;
    *) export PATH="$subpath:$PATH";;
esac


# Conda
CONDA_INIT_SCRIPT="$local_dir/conda/etc/profile.d/conda.sh" 
[ -f $CONDA_INIT_SCRIPT ] && . $CONDA_INIT_SCRIPT


_confirm_run() {
    read -p "$1[confirm]:" -n 1 key
    if [ "$key" = "" ]; then
        eval "$1"
    fi
}

cf() {
    cmd=$(complete-fzf --alias="`alias`" --command="$*")
    _confirm_run "$cmd"
}

cr() {
    cmd=`history | sed 's/\s\+[0-9]\+\s\+//g' | sort -rn | awk '!x[$0]++' | fzf --layout=reverse --prompt='Cmd> '`
    _confirm_run "$cmd"
}

ensure_ssh_agent() {
    export SSH_AUTH_SOCK=`sock_ssh.py`
}

chpwd() {
    command -v zoxide >/dev/null 2>&1 && zoxide add `pwd`
    [ -f ".git/pynq" ] && conda activate `cat .git/pynq`
}

ltmux() {
    if ! echo "$TMUX"|egrep ".*alacritty.*" >/dev/null; then
        echo "not in a alacritty tmux session"
    fi
    tmux rename-window local
    unset TMUX
    tmux $@
}

# fzf
export FZF_DEFAULT_COMMAND="fd --type file --follow --color=never --hidden --exclude '.git'"
export FZF_DEFAULT_OPTS="--ansi -m --color dark --bind=ctrl-l:toggle-all --bind=ctrl-d:preview-half-page-down --bind=ctrl-u:preview-half-page-up --bind=ctrl-/:toggle-preview --inline-info --preview-window wrap --height=10"

# Basic settings
export EDITOR=vim
export LANG=en_US.UTF-8
export LC_ALL=$LANG
export TERM="xterm-256color"
export PYTHONPATH="."

alias ls='ls --color'
alias ll='ls --color -alh'

alias grep='grep --color=auto'
alias abrew='arch -arm64 brew'
alias g='git'
alias pipx="$HOME/.local/conda/bin/python -m pip"
alias Lg='lazygit'
alias d='docker'
alias dc='docker-compose'
alias sv="sudo supervisorctl"

alias zdd='zoxide add "`pwd`"'
alias zclear='zoxide query -l | xargs zoxide remove'
alias zl='zoxide query -l -s'

alias bat='bat -p'
alias m='bat --language=man --color=always'
export BAT_THEME="Solarized (dark)"


[ -f "$HOME/.platformrc" ] && . "$HOME/.platformrc"

#### Advanced shells start ####
zsh_cfg() {
    setopt SHARE_HISTORY
    setopt INC_APPEND_HISTORY
    setopt HIST_IGNORE_DUPS
    setopt HIST_IGNORE_ALL_DUPS
    setopt HIST_IGNORE_SPACE
    setopt HIST_SAVE_NO_DUPS
    setopt HIST_VERIFY
    setopt PROMPT_SUBST
    WORDCHARS=${WORDCHARS//[\/]}
    HISTFILE="${ZDOTDIR:-${HOME}}/.zhistory"
    SAVEHIST=5000; HISTSIZE=2000
    autoload -Uz compinit && compinit -C && zmodload zsh/complist
    zstyle ':completion:*' menu yes select
    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
    bindkey -e && bindkey -M menuselect '/' history-incremental-search-forward
    bindkey '^U' backward-kill-line

    # zsh syntax begin
    . "$local_dir/zsh-autosuggestions/zsh-autosuggestions.zsh"
    . "$local_dir/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

    fzf-history-widget() {
      selected=`history -n 0 |awk '!x[$0]++' |FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS -e +s +m --tac --query ${(qqq)LBUFFER} --layout=reverse" fzf --prompt="History Commands: > "`
      BUFFER=$selected; CURSOR=$#BUFFER; zle redisplay
    }
    zle -N fzf-history-widget && bindkey '^R' fzf-history-widget

    fzf-complete-widget() {
      BUFFER=$(complete-fzf --alias="`alias`" --command="$LBUFFER"); CURSOR=$#BUFFER; zle redisplay
    }
    zle -N fzf-complete-widget && bindkey '^T' fzf-complete-widget

    zoxide_widget() {
        directory="$(zoxide query -l | fzf --layout=reverse --prompt='Directory: > ')"
        [ -n "$directory" ] && directory="cd $directory"
        BUFFER="$directory"; CURSOR=$#BUFFER; zle redisplay
    }
    zle -N zoxide_widget && bindkey '^G' zoxide_widget
    
    printcolors() {
        for i in {0..255} ; do
            printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
            if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
                printf "\n";
            fi
        done
    }
   
    # PROMPT
    precmd() {
        [ -e ".git" ] && __git_branch=`git rev-parse --abbrev-ref HEAD 2>/dev/null` &&\
            [ -n $__git_branch ] && __git_branch=" $__git_branch" || __git_branch=""
    }
    LOCAL_MACHINE_NAME=`hostname`
    PROMPT=$'%(?:%F{2}:%F{1})${LOCAL_MACHINE_NAME:->} %B%F{4}%c%b%F{8}${__git_branch}%f%{$reset_color%} %# '

    alias ls='lsd --icon=never'
    alias ll='lsd --icon=never -alh'
}

bash_cfg() {
    __zoxide_to_directory__() {
        if [ `zoxide query -l | wc -l` -lt 1 ]; then
            zindex.py -c /home/ops -d 5 >/dev/null
            echo "zoxide indexed: zindex.py -c /home/ops -d 5"
        fi
        directory="$(zoxide query -l | fzf --layout=reverse --prompt='Directory: > ')"
        [ -n "$directory" ] && directory="cd $directory"
        READLINE_LINE="$directory"
        READLINE_POINT=0x7fffffff
    }
    bind -x '"\C-g": __zoxide_to_directory__'

    __fzf_complete__() {
      output=$(complete-fzf --alias="`alias`" --command="$READLINE_LINE")
      READLINE_LINE="$output"
      READLINE_POINT=0x7fffffff
    }
    bind -x '"\C-t": __fzf_complete__'

    __fzf_history__() {
      local output opts script
      opts="-n2..,.. --scheme=history +m --read0"
      script='BEGIN { getc; $/ = "\n\t"; $HISTCOUNT = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCOUNT - $. . "\t$_" if !$seen{$_}++'
      output=$(
        builtin fc -lnr -2147483648 |
          last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e "$script" |
          FZF_DEFAULT_OPTS="$opts" fzf --query "$READLINE_LINE" --prompt="History Commands: > "
      ) || return
      READLINE_LINE=${output#*$'\t'}
      if [[ -z "$READLINE_POINT" ]]; then
        echo "$READLINE_LINE"
      else
        READLINE_POINT=0x7fffffff
      fi
    }
    bind -x '"\C-r": __fzf_history__'

    # if command -v tmux &> /dev/null; then
    #     if [[ $- =~ i ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_TTY" ]]; then
    #         tmux a -t0 || tmux
    #     fi
    # fi
    # end bash
    #
    alias d='sudo docker'
    alias dc='sudo docker-compose'
    [ -f "$HOME/.tmux.conf" ] && tmux source-file ~/.tmux.conf
}

if command -v zle &> /dev/null; then
    zsh_cfg
elif command -v bind &> /dev/null; then
    bash_cfg
fi
#### Advanced shells end ####

if [ "$TERM_PROGRAM" != "vscode" ] && test -n $SSH_TTY && tmux ls | grep run; then
    tmux attach -t run
fi
