"if get(s:, 'loaded', 0) != 0 | finish | else | let s:loaded = 1 | endif
set encoding=utf-8 fileencodings=utf-8,ucs-bom,gbk,gb18030,big5,euc-jp,latin1
let mapleader = "\<space>"

set nocompatible hidden wrap
set hlsearch incsearch ignorecase smartcase
set backspace=indent,eol,start
set completeopt=menu,preview
set noswapfile nobackup nowritebackup
set cindent autoindent smartindent expandtab smarttab
set nu signcolumn=number laststatus=1 mouse=v cursorline
set wildignore+=.bak,*.swp,*.class,*.pyc,*DS_Store*,*.swp,*/.Trash/*
set updatetime=1000
set autoread autowrite
set ts=4 sw=4 sts=4 scrolloff=3
set statusline=%F\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P

syntax on
filetype plugin indent on
nnoremap <c-c> :q<cr>
nnoremap - :Explore<cr>
for [k, v] in items({"<c-b>": "<left>", "<c-f>": "<right>",
\"<c-a>": "<home>","<c-e>": "<end>", "<c-d>": "<del>"})
    exe "inoremap ".k." ".v | exe "cnoremap ".k." ".v
endfor

" Plugins
silent! call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'jiangmiao/auto-pairs'
Plug '907th/vim-auto-save'
Plug 'sbdchd/neoformat'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'tpope/vim-commentary'
Plug 'skywind3000/asyncrun.vim'
Plug 'tomasiser/vim-code-dark'
silent! call plug#end()

" Basic settings
let g:asyncrun_open = 8

nnoremap = :Neoformat<cr>
let g:neoformat_basic_format_align = 1
let g:neoformat_basic_format_trim = 1
let g:neoformat_python_iosrt = {
    \ 'exe': 'isort',
    \ 'args': ['--profile=black'],
    \ }
let g:neoformat_enabled_python = ['isort', 'black']
au FileType python let b:neoformat_run_all_formatters = 1
let g:neoformat_rust_rustfmt = {
    \ 'exe': 'rustfmt',
    \ 'args': ['--emit=stdout', '--edition=2021'],
    \ }

let g:auto_save = 1
let g:netrw_dirhistmax = 0

noremap  <c-j>      :<C-U>call fzf#vim#files('')<CR>
noremap  <c-h>      :<C-U>call fzf#vim#history()<CR>
nnoremap <leader>m  :<C-U>call fzf#vim#marks()<CR>
nnoremap <leader>n  :<C-U>Commands<CR>
nnoremap <leader>t  :<C-U>BTags<CR>
nnoremap <leader>y  :<C-U>Tags<CR>
nnoremap <leader>h  :<C-U>Helptags<CR>
nnoremap <leader>r  y:<C-U><C-R>=printf("Tags %s", expand("<cword>"))<CR>
nnoremap <leader>w  y:<C-U><C-R>=printf("Rg %s", expand("<cword>"))<CR>
nnoremap <leader>s  :<C-U><C-R>=printf("Rg ")<CR>
nnoremap <leader>j  :History:<CR>
let g:fzf_layout = { 'window': 'enew' }
let g:fzf_commits_log_options =  "-200 --color=always"
let g:fzf_preview_window = ['up:80%', 'ctrl-/']

" Custom Script
function! CreatePlayGround(fileName)
    let l:directory = expand('~/.config/playground')
    if !isdirectory(l:directory)
        call mkdir(l:directory)
    endif
    let l:ext = fnamemodify(a:fileName, ':e')
    if index(["go", "py"], l:ext) < 0
        echo "Only go,py supported. You typed: ".l:ext
        return
    endif
    exe 'edit '.l:directory.'/'.a:fileName
endfunction
command! -nargs=1 CreatePlayGround call CreatePlayGround(<f-args>)

function! s:GoToWorkspace(directory)
    execute 'cd '.a:directory
    execute 'Files'
    if exists(":CocRestart") | execute 'CocRestart' | endif
endfunction
command! Workspaces call fzf#run(fzf#wrap({
      \ 'source': 'zoxide query -l',
      \ 'sink': function('s:GoToWorkspace'),
      \ 'options': '--prompt "Workspace> " '
      \ }))

command! Lg execute '!tmux popup -d "\#{pane_current_path}" -xC -yC -w99\% -h99\% -E "zsh -i -c lazygit"'
command! LoadCopilot exe 'call plug#load("copilot.vim")'

" Auto Cmd
augroup vimrc
    au FileType javascript,html,vue setlocal sw=2 ts=2 sts=2
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g'\"" | endif
    au FileType python nnoremap <leader>b :AsyncRun python %<cr>
    au FileType go nnoremap <leader>b :AsyncRun go run %<cr>
    au FileType json syntax match Comment +\/\/.\+$+
augroup END


" Theme
try | colorscheme codedark | catch /.*/ | endtry
for g in ['Normal', 'EndOfBuffer', 'LineNr', "Directory"]
    exe "hi ".g." ctermbg=NONE guibg=NONE" | endfor
hi clear CursorLine
hi CursorLine ctermbg=237 guibg=#386641
hi LineNr ctermfg=238
hi SpellBad ctermbg=17
hi StatusLine ctermbg=58 guibg=#6a994e
hi StatusLineNC ctermbg=244 guibg=#6d6875
hi Search ctermbg=240 guibg=#03045e
hi Visual ctermbg=240 guibg=#03045e
hi VisualNOS ctermbg=240 guibg=#03045e
hi PmenuSel ctermbg=22 guibg=#03045e ctermfg=255 guifg=#ffffff


" Neovim Nvim
if has('nvim')
let g:coq_settings = { 'auto_start': v:true,
        \ 'display.icons.mode': 'none',
        \ 'display.ghost_text.enabled': v:false,
        \ 'display.pum.x_truncate_len': 18,
        \ 'clients.tags.enabled': v:false,
        \ 'clients.tree_sitter.enabled': v:false,
        \ 'clients.tmux.enabled': v:false,
        \ 'clients.lsp.always_on_top': [],
        \ 'keymap.jump_to_mark': '<c-l>',
        \ }
inoremap <silent><expr> <CR> pumvisible() ? (complete_info().selected == -1 ? "\<C-e>" : "\<C-y>") : "\<CR>"

let g:fzf_lsp_command_prefix = "Lsp"
nnoremap <leader>a   :<C-u>LspDiagnostics<CR>

lua <<EOF
local ensure_packer = function()
    local install_path = vim.fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
    if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
        vim.fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
        vim.cmd [[packadd packer.nvim]]
        return true
    end
    return false
end
local packer_bootstrap = ensure_packer()
require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'nvim-lua/plenary.nvim'

    use 'neovim/nvim-lspconfig'
    use 'williamboman/mason.nvim'
    use 'williamboman/mason-lspconfig.nvim'
    use 'gfanto/fzf-lsp.nvim'

    use 'github/copilot.vim'
    use {'ms-jpq/coq_nvim', branch = 'coq'}
    use {'ms-jpq/coq.artifacts', branch = 'artifacts'}

    if packer_bootstrap then
        require('packer').sync()
    end
end)

local coq = require('coq')
local lspconfig = require('lspconfig')

-- https://github.com/neovim/nvim-lspconfig
local on_attach = function(client, bufnr)
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
  local bufopts = { noremap=true, silent=false, buffer=bufnr }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
  vim.keymap.set('n', 'gk', vim.lsp.buf.hover, bufopts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
  vim.keymap.set('n', 'gs', vim.lsp.buf.signature_help, bufopts)
  vim.keymap.set('n', 'gt', vim.lsp.buf.type_definition, bufopts)
  vim.keymap.set('n', 'ga', vim.lsp.buf.rename, bufopts)
  vim.keymap.set('n', 'ge', vim.lsp.buf.code_action, bufopts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
end

local lsp_flags = { debounce_text_changes = 150, }
lspconfig['gopls'].setup(coq.lsp_ensure_capabilities({
    on_attach = on_attach,
    flags = lsp_flags,
}))
lspconfig['pyright'].setup(coq.lsp_ensure_capabilities({
    on_attach = on_attach,
    flags = lsp_flags,
    settings = {python = {analysis = {
        reportOptionalSubscript = 'none',
        reportGeneralTypeIssues = 'none',
        reportOptionalOperand = 'warning',
        reportOptionalMemberAccess = 'none'
    }}}
}))

-- https://github.com/williamboman/mason.nvim
-- https://github.com/williamboman/mason-lspconfig.nvim
require("mason").setup({
    ui = {icons = {
            package_installed = "✓",
            package_pending = "➜",
            package_uninstalled = "✗"
        }}
})
require("mason-lspconfig").setup {
    ensure_installed = {"pyright", "gopls"},
}
-- https://github.com/gfanto/fzf-lsp.nvim
require('fzf_lsp').setup({
    override_ui_select = true,
})
EOF
endif
