set encoding=utf-8
let mapleader = "\<space>"

set nocompatible hidden wrap
set hlsearch incsearch ignorecase smartcase
set backspace=indent,eol,start
set completeopt=menu,menuone,noselect
set noswapfile nobackup nowritebackup
set cindent autoindent smartindent expandtab smarttab
set nu signcolumn=number laststatus=1 mouse=v cursorline
set autoread autowrite
set ts=4 sw=4 sts=4 scrolloff=3
set statusline=%F\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P
set wildignore+=.bak,*.swp,*.class,*.pyc,*DS_Store*,*.swp,

nnoremap <C-c> :q<CR>
nnoremap -     :Explore<CR>
nnoremap [q    :cprevious<CR>
nnoremap ]q    :cnext<CR>

inoremap <C-b> <left>
cnoremap <C-b> <left>
inoremap <C-f> <right>
cnoremap <C-f> <right>
inoremap <C-a> <home>
cnoremap <C-a> <home>
inoremap <C-e> <end>
cnoremap <C-e> <end>

" Plugins
set rtp+=~/.vim
if empty(glob('~/.vim/autoload/plug.vim'))
    execute '!curl --silent -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
if !empty(glob($HOME..'/nq/bin'))
    let $PATH = $HOME..'/nq/bin:'..$PATH
endif
silent! call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf',
Plug 'junegunn/fzf.vim',
Plug 'tpope/vim-commentary',
Plug 'tpope/vim-surround',
Plug 'tpope/vim-fugitive',
Plug 'jiangmiao/auto-pairs',
Plug '907th/vim-auto-save',
Plug 'sbdchd/neoformat',
Plug 'AndrewRadev/splitjoin.vim',
Plug 'skywind3000/asyncrun.vim'

Plug 'easymotion/vim-easymotion'
Plug 'mg979/vim-visual-multi'
Plug 'vim-scripts/ReplaceWithRegister'
Plug 'wellle/targets.vim'
Plug 'michaeljsmith/vim-indent-object'
silent! call plug#end()

nnoremap = :Neoformat<CR>
let g:neoformat_basic_format_align = 1
let g:neoformat_basic_format_trim = 1
let g:neoformat_python_iosrt = {
    \ 'exe': 'isort',
    \ 'args': ['--profile=black'],
    \ }
let g:neoformat_enabled_python = ['isort', 'black']
au FileType python let b:neoformat_run_all_formatters = 1
let g:neoformat_rust_rustfmt = {
    \ 'exe': 'rustfmt',
    \ 'args': ['--emit=stdout', '--edition=2021'],
    \ }

let g:auto_save = 1
let g:netrw_dirhistmax = 0

noremap  <c-j>      :<C-U>call fzf#vim#files('')<CR>
noremap  <c-h>      :<C-U>call fzf#vim#history()<CR>
nnoremap <leader>m  :<C-U>call fzf#vim#marks()<CR>
nnoremap <leader>n  :<C-U>Commands<CR>
nnoremap <leader>t  :<C-U>BTags<CR>
nnoremap <leader>y  :<C-U>Tags<CR>
nnoremap <leader>h  :<C-U>Helptags<CR>
nnoremap <leader>r  y:<C-U><C-R>=printf("Tags %s", expand("<cword>"))<CR>
nnoremap <leader>w  y:<C-U><C-R>=printf("Rg %s", expand("<cword>"))<CR>
nnoremap <leader>s  :<C-U><C-R>=printf("Rg ")<CR>
nnoremap <leader>j  :History:<CR>
let g:fzf_layout = { 'window': 'enew' }
let g:fzf_commits_log_options =  "-200 --color=always"
let g:fzf_preview_window = ['up:80%', 'ctrl-/']

function! s:GoToWorkspace(directory)
    execute 'cd '.a:directory
    execute 'Files'
    if exists(":CocRestart") | execute 'CocRestart' | endif
endfunction
command! Workspaces call fzf#run(fzf#wrap({
      \ 'source': 'zoxide query -l',
      \ 'sink': function('s:GoToWorkspace'),
      \ 'options': '--prompt "Workspace> " '
      \ }))

command! Lg execute '!tmux popup -d "\#{pane_current_path}" -xC -yC -w99\% -h99\% -E "zsh -i -c lazygit"'


" Auto cmd group
augroup vimrc
    au FileType javascript,html,vue setlocal sw=2 ts=2 sts=2
    au FileType qf set nonu
    au FileType python let b:neoformat_run_all_formatters = 1
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g'\"" | endif
augroup END


" Theme
colorscheme habamax
for g in ['Normal', 'EndOfBuffer', 'LineNr', "Directory"]
    exe "hi ".g." ctermbg=NONE guibg=NONE" | endfor
hi clear CursorLine
hi CursorLine ctermbg=237 guibg=#386641
hi LineNr ctermfg=238 ctermbg=NONE guifg=#386641 guibg=NONE
hi SpellBad ctermbg=17 guibg=#959595
hi StatusLine ctermbg=58 guibg=#6a994e
hi StatusLineNC ctermbg=244 guibg=#6d6875
hi Search ctermbg=240 guibg=#03045e
hi Visual ctermbg=240 guibg=#03045e
hi VisualNOS ctermbg=240 guibg=#03045e
hi PmenuSel ctermbg=22 ctermfg=255 guibg=#03045e guifg=#ffffff
